#!/usr/bin/env bash
# Script to install and configure Nginx with redirection

# Update and install Nginx
apt-get -y update
apt-get -y install nginx

# Create the default page
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
    }
}
EOF

# Restart Nginx
service nginx restart

